spring.application.name=needle-flow

spring.datasource.url=jdbc:postgresql://localhost:5432/needle_flow
spring.datasource.username=username
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=never
spring.sql.init.schema-locations=classpath:db/schema.sql
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=10MB