services:
  postgres:
    image: postgres:17
    container_name: needle-flow-db
    environment:
      POSTGRES_DB: needle_flow
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db-data: